### ISSUE TITLE
初期データ用のクエリを自動実行されるようにする

### ISSUE THREAD

**Issue by knanbu** [nstgurano/Todo#10]
現状: 環境を初回起動した際、mysqlのコンテナから直接sql文を叩いてテーブル作成等を行うことになる

ymlのvolumesに
`- ./mysql/initdb.d:/docker-entrypoint-initdb.d`
のようなマウントを追加し、指定したホスト側のフォルダ(↑の場合./myspl/initdb.d)に初期実行したいsqlを書いたファイルを入れましょう

**Comment by nstgurano** [comment]
修正完了です。
PDOのユーザーとパスワードも変更しました
