### ISSUE TITLE
ログイン画面のレイアウトが崩れる現象

### ISSUE THREAD

**Issue by knanbu** [nstgurano/Todo#11]
パスワード間違い等でログインに失敗した際の画面のレイアウトが崩れてしまします。
(バリデーションエラーメッセージを表示することが関係している？)

加えて、リロードや左上のアイコンクリックでログイン画面に行き直してもバリデーションエラーメッセージが表示されっぱなしになっています。

**Comment by nstgurano** [comment]
完了

**Comment by knanbu** [comment]
エラーメッセージは消えますが、メールアドレスとパスワードの入力欄が中央揃えから崩れる現象がそのままな気がします
