### ISSUE TITLE
タスク新規作成画面でカテゴリー追加を行った際の不具合

### ISSUE THREAD

**Issue by knanbu** [nstgurano/Todo#12]
タスクの新規作成画面でカテゴリーの追加を行うと以下3つの現象が起きます

1. 画面がタスク編集画面に変わる
2. カテゴリー選択部分にphpのエラー分が表示される
3. カテゴリー追加の部分に「空白です」というバリデーションエラメッセージが表示される

おそらく2と3は誤ったページ遷移が発生してることによるものだと思われるので、1を解消しましょう

**Comment by nstgurano** [comment]
完了
