### ISSUE TITLE
認証後に開ける各画面のアクセス時に認証チェックを入れる

### ISSUE THREAD

**Issue by knanbu** [nstgurano/Todo#15]
ログアウトを行った後にブラウザバックでタスク一覧画面に戻り、タスク追加やアカウント設定画面等にアクセスできてしまうので、ログイン後に開ける全ての画面に対して逐一認証状態のチェック処理を追加する。

**Comment by nstgurano** [comment]
完了

**Comment by knanbu** [comment]
まだどの画面も普通にアクセスできちゃいますね
