### ISSUE TITLE
タスク編集画面のフォームに初期値を置く

### ISSUE THREAD

**Issue by knanbu** [nstgurano/Todo#2]
現状: タスクの詳細カード的な領域(青い部分)に既に登録されているデータが表示され、別のカード(オレンジの部分)に編集用の空フォームが配置されている状態

これはタスクの詳細画面なのか編集画面なのかよく分からない感じになるので、編集フォームの初期値に登録データを予め入れてページを表示するように変更しましょう。
編集画面でもタスクの新規追加を行う場合もあると思うので、レイアウトはタスク新規登録のページのものをそのまま使えばいいです。

もしタスクの詳細画面としての役割も兼ねていたなら別で現行の青カードのみを表示するページを作りましょう。
その場合ページを分けるので編集と詳細それぞれの画面へのアクセス方法も用意する必要有り

ついでに編集画面の「登録」ボタンを「更新」や「保存」等別の文言に変えましょう

**Comment by nstgurano** [comment]
初期値を登録データに変更完了
ボタンの文言変更完了
レイアウトも完了

タスクの詳細画面　未着手
