### ISSUE TITLE
アカウント設定系の画面でカテゴリ一覧のサイドバーが表示されている

### ISSUE THREAD

**Issue by knanbu** [nstgurano/Todo#20]
タスクの新規作成/編集画面ではサイドバーが表示されていないのに対し、アカウント設定画面とそこから行ける画面には表示されています。
必要ないと思うので表示しない様に変更しましょう

**Comment by nstgurano** [comment]
完了

**Comment by knanbu** [comment]
アカウント設定画面は消えてますけど、名前変更とかの画面は変わってないですね
あとサイドバーが完全に無いと全体的なレイアウトの統一感がなくなるなって思ったので、やっぱりサイドバー自体は設置しておいて中身を「タスク一覧に戻る」みたいなボタンだけ置いておきましょうか

**Comment by nstgurano** [comment]
あー、なるほど
了解です！

**Comment by nstgurano** [comment]
アカウント設定周りのサイドバーをすべて修正しました。
ただ、余白も多く寂しい感じではあります。
いい感じに修正できたら修正していこうかと思います
