### ISSUE TITLE
アカウント設定、ログアウトをどの画面からでもアクセス可能にする

### ISSUE THREAD

**Issue by knanbu** [nstgurano/Todo#21]
今の所タスク一覧のサイドバーのみにこれらが配置されていて、タスク新規作成や編集の画面ではサイドバーが無いからログアウト操作ができない状態なので、どの画面からでも操作可能な状態にしましょう
カテゴリの編集/削除のメニューが完成したら、それを流用してヘッダー右端にでもメニューを設置するといいと思います

**Comment by nstgurano** [comment]
サイドバーのアカウント設定とログアウトを消して、ヘッダーに移動し完了
