### ISSUE TITLE
「戻る」ボタンの設置

### ISSUE THREAD

**Issue by knanbu** [nstgurano/Todo#24]
- タスク新規作成画面
- タスク編集画面
- 名前変更画面
- メールアドレス変更画面
- パスワード変更画面

に対して前のページに戻る(「キャンセル」等の表記でもいい)ボタンを設置しましょう
この時、「登録」や「更新」等のボタンとは少し距離を離して並べ、色を変えるとUI的に尚良いです

**Comment by nstgurano** [comment]
完了
カテゴリー編集にも加え、退会もUIを変えています
