### ISSUE TITLE
別のユーザーのタスク詳細/編集画面にアクセスできてしまう

### ISSUE THREAD

**Issue by knanbu** [nstgurano/Todo#28]
ユーザーAが登録したとあるタスクのIDが3だとした時、ユーザーBのアカウントで認証されている状態でタスク詳細/編集画面に行き、urlのtask_id部分を3に書き換えてアクセスすると問題なく画面が表示されてしまいます。
他アカウントのデータを表示したり編集したりできないよう画面アクセスの制限をかけるようにしましょう

**Comment by nstgurano** [comment]
完了

**Comment by knanbu** [comment]
セッションでの制御だとaタグのherfにあるtask_idを書き換えるだけでアクセスできてしまうので、ちゃんとユーザーアカウントのIDを確認するようにしましょう

**Comment by nstgurano** [comment]
了解です

**Comment by knanbu** [comment]
画面へのアクセスだけでなく、一応タスクとカテゴリの削除にもユーザーアカウントの確認処理入れましょうか

**Comment by nstgurano** [comment]
アカウントIDで確認して、一応エラー文も表示しました。
ただ、意図的に値を変えないと他のユーザーのデータを変更できないので、エラー文は必要ないのかなと思ったりです。

**Comment by knanbu** [comment]
別にあっても困ることはないのでエラー文は残したままで大丈夫です
