### ISSUE TITLE
タスク一覧画面左のサイドバーのレイアウト修正

### ISSUE THREAD

**Issue by knanbu** [nstgurano/Todo#6]
現状: 
・タスクの新規追加ボタンが「＋」のみの表記なので分かりづらい
・メニューの幅が固定
・カテゴリが文字数によっては複数行で表示される
・カテゴリの編集/削除ボタンがカテゴリと並んで配置されているので、誤クリックを招く可能性がある
・登録されたカテゴリが増えてくると「アカウント設定」と「ログアウト」ボタンに文字が被る

修正後:
・「＋」表記のボタンから「タスク新規登録」等のはっきり分かる文言に変更する
・メニューの幅がウィンドウサイズによって変化(実数値は任せるが、width: 20%、max-width: 300pxのような設定をする)
・文字数の多いカテゴリ名はある程度の幅を超えた部分については「...」などの表記に変更する(overflow: hidden)。「ある程度の幅」も多分％指定できるからウィンドウサイズによって変化するようにできる
・編集/削除ボタンを右クリックのオリジナルメニューに移動させる(これに関しては理想論なので他より重要度少し低め。JSがきついなら他の措置を考える)
・多分仮置きだと思われるが、そもそも「アカウント設定」と「ログアウト」ボタンがど真ん中にあるのはおかしいので配置を変更、カテゴリ表示部分はoverflow: scroll等を適用する

**Comment by nstgurano** [comment]
完了
