### ISSUE TITLE
何も選択せずにタスクの削除ボタンを押した場合のエラー解消

### ISSUE THREAD

**Issue by knanbu** [nstgurano/Todo#7]
現状; タスク一覧画面で、タスクの左に設置されているセレクトボックスを1つも選択しないまま「削除」ボタンを押すとphpのエラー画面に遷移する

「選択されたタスクIDのリストを使って消そうとしているが、IDが1つも入っていないリストだから消せない」という挙動だと思われるので、削除処理を行う前に選択されたタスクIDリストの要素数をチェックするように修正しましょう

**Comment by nstgurano** [comment]
完了
