### ISSUE TITLE
認証している状態でログイン画面にアクセスした際のリダイレクト

### ISSUE THREAD

**Issue by knanbu** [nstgurano/Todo#8]
現状; いずれかのユーザーでログインしている状態で、functions/view/login.view.phpにアクセスするとログイン画面(その他の認証前で使用する画面も)が表示されてしまう(ついでに認証も解かれる？

ログインした状態で認証前の画面にアクセスした際はタスク一覧画面にリダイレクトされるような処理を加えましょう

**Comment by nstgurano** [comment]
完了
