### ISSUE TITLE
タスク一覧画面のレイアウト修正

### ISSUE THREAD

**Issue by knanbu** [nstgurano/Todo#9]
現状; 画面サイズがウィンドウサイズより常に大きくなっているせいで無駄にスクロールバーが出ている

おそらくヘッダーとフッターのheightの分だけ画面サイズの方が大きくなっているので、一覧表示部分のheightを調整しましょう

**Comment by nstgurano** [comment]
完了

**Comment by knanbu** [comment]
ウィンドウの縦サイズが一定サイズ以上になるとフッターが変に浮いた状態になるので
http://webnonotes.com/css/header_footer/
辺りを参考にして全体を配置し直してみてください
